import localFont from "next/font/local";
import "./globals.css";
import Barra from "./componentes/Barra";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
function Cargando() {
  return <img className="cargando" src="/cargando.gif"></img>;
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Barra/>
       <Suspense fallback={Cargando()}>

       <main>
        {children}
        </main> 
       </Suspense>
      </body>
    </html>
  );
}
